<a href="https://colab.research.google.com/github/ayushpaliwal1920/Deep_Learning/blob/main/23_HyperparameterTuning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [152]:
import pandas as pd
import numpy as np

In [153]:
df = pd.read_csv("diabetes.csv")
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [154]:
# checking correlation btwn data :

df.corr()['Outcome']

Pregnancies                 0.221898
Glucose                     0.466581
BloodPressure               0.065068
SkinThickness               0.074752
Insulin                     0.130548
BMI                         0.292695
DiabetesPedigreeFunction    0.173844
Age                         0.238356
Outcome                     1.000000
Name: Outcome, dtype: float64

In [155]:
# seperate data :

x = df.iloc[:,:-1].values
y = df.iloc[:,-1].values

In [156]:
# scaling :

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

x = scaler.fit_transform(x)

In [157]:
# train test split

from sklearn.model_selection import train_test_split

x_train , x_test , y_train , y_test = train_test_split(x,y,test_size= 0.2, random_state=42)

In [158]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense , Dropout

In [159]:
model = Sequential()

model.add(Dense(32,activation='relu',input_dim=8))

model.add(Dense(1,activation='sigmoid'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [160]:
# compile

model.compile(optimizer="Adam" , loss = "binary_crossentropy" , metrics =['accuracy']);

In [161]:
model.fit(x_train,y_train , epochs = 50 , batch_size= 32,validation_data = (x_test , y_test))

Epoch 1/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step - accuracy: 0.4577 - loss: 0.7713 - val_accuracy: 0.5519 - val_loss: 0.6943
Epoch 2/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.5586 - loss: 0.6818 - val_accuracy: 0.6818 - val_loss: 0.6348
Epoch 3/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6629 - loss: 0.6176 - val_accuracy: 0.7208 - val_loss: 0.5964
Epoch 4/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7378 - loss: 0.5750 - val_accuracy: 0.7662 - val_loss: 0.5721
Epoch 5/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7606 - loss: 0.5459 - val_accuracy: 0.7597 - val_loss: 0.5561
Epoch 6/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7638 - loss: 0.5227 - val_accuracy: 0.7727 - val_loss: 0.5442
Epoch 7/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7655 - loss: 0.5062 - val_accuracy: 0.7597 - val_loss: 0.5388
Epoch 8/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7704 - loss: 0.4943 - val_accuracy: 0.7662 - val_loss: 0.5339
Epoch 9/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7720 - loss: 0.4861 - val_accuracy: 0.7727 - val_loss: 0.5301
Epoch 10/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7704 - loss: 0.4794 - val_accuracy: 0.7662 - val_loss: 0.5274
Epoch 11/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7752 - loss: 0.4747 - val_accuracy: 0.7662 - val_loss: 0.5254
Epoch 12/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7752 - loss: 0.4708 - val_accuracy: 0.7597 - val_loss: 0.5203
Epoch 13/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7736 - loss: 0.4680 - val_accuracy: 0.7597 - val_loss: 0.5199
Epoch 14/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7720 - loss: 0.4648 - val_accuracy: 0.7662 - val_loss: 0.5190
Epoch 15/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7720 - loss: 0.4621 - val_accuracy: 0.7727 - val_loss: 0.5185
Epoch 16/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7704 - loss: 0.4593 - val_accuracy: 0.7662 - val_loss: 0.5191
Epoch 17/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7752 - loss: 0.4570 - val_accuracy: 0.7727 - val_loss: 0.5186
Epoch 18/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7801 - loss: 0.4546 - val_accuracy: 0.7662 - val_loss: 0.5169
Epoch 19/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7769 - loss: 0.4532 - val_accuracy: 0.7532 - val_loss: 0.5176
Epoch 20/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7769 - loss: 0.4510 - val_accuracy: 0.7532 - val_loss: 0.5193
Epoch 21/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7769 - loss: 0.4492 - val_accuracy: 0.7468 - val_loss: 0.5190
Epoch 22/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7752 - loss: 0.4479 - val_accuracy: 0.7597 - val_loss: 0.5159
Epoch 23/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4463 - val_accuracy: 0.7468 - val_loss: 0.5178
Epoch 24/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4445 - val_accuracy: 0.7532 - val_loss: 0.5182
Epoch 25/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7801 - loss: 0.4436 - val_accuracy: 0.7403 - val_loss: 0.5196
Epoch 26/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7866 - loss: 0.4422 - val_accuracy: 0.7468 - val_loss: 0.5186
Epoch 27/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4409 - val_accuracy: 0.7468 - val_loss: 0.5197
Epoch 28/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4399 - val_accuracy: 0.7468 - val_loss: 0.5223
Epoch 29/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4386 - val_accuracy: 0.7468 - val_loss: 0.5215
Epoch 30/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4376 - val_accuracy: 0.7532 - val_loss: 0.5217
Epoch 31/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4368 - val_accuracy: 0.7597 - val_loss: 0.5201
Epoch 32/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4362 - val_accuracy: 0.7532 - val_loss: 0.5203
Epoch 33/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4345 - val_accuracy: 0.7597 - val_loss: 0.5210
Epoch 34/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4342 - val_accuracy: 0.7468 - val_loss: 0.5210
Epoch 35/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4334 - val_accuracy: 0.7597 - val_loss: 0.5220
Epoch 36/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4326 - val_accuracy: 0.7468 - val_loss: 0.5232
Epoch 37/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4317 - val_accuracy: 0.7468 - val_loss: 0.5246
Epoch 38/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4312 - val_accuracy: 0.7532 - val_loss: 0.5251
Epoch 39/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7883 - loss: 0.4298 - val_accuracy: 0.7597 - val_loss: 0.5236
Epoch 40/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4295 - val_accuracy: 0.7532 - val_loss: 0.5230
Epoch 41/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4287 - val_accuracy: 0.7597 - val_loss: 0.5216
Epoch 42/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7915 - loss: 0.4278 - val_accuracy: 0.7597 - val_loss: 0.5227
Epoch 43/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4266 - val_accuracy: 0.7597 - val_loss: 0.5240
Epoch 44/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4264 - val_accuracy: 0.7662 - val_loss: 0.5254
Epoch 45/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4253 - val_accuracy: 0.7468 - val_loss: 0.5265
Epoch 46/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7932 - loss: 0.4246 - val_accuracy: 0.7662 - val_loss: 0.5262
Epoch 47/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4239 - val_accuracy: 0.7727 - val_loss: 0.5269
Epoch 48/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4235 - val_accuracy: 0.7532 - val_loss: 0.5296
Epoch 49/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4225 - val_accuracy: 0.7727 - val_loss: 0.5286
Epoch 50/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8013 - loss: 0.4220 - val_accuracy: 0.7662 - val_loss: 0.5273

# HyperParameter Tuning

In [162]:
# 1. how to select appropriate optimizer
# 2. how to select no. of nodes in a layer
# 3. howw to select no. of layers
# 4. All in one

In [163]:
pip install -U keras-tuner

Requirement already satisfied: keras-tuner in /usr/local/lib/python3.12/dist-packages (1.4.8)
Requirement already satisfied: keras in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (3.13.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (26.0)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (2.32.4)
Requirement already satisfied: kt-legacy in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (1.0.5)
Requirement already satisfied: grpcio in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (1.80.0)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (5.29.6)
Requirement already satisfied: typing-extensions~=4.12 in /usr/local/lib/python3.12/dist-packages (from grpcio->keras-tuner) (4.15.0)
Requirement already satisfied: absl-py in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (1.4.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (2.0.2)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (0.1.0)
Requirement already satisfied: h5py in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (3.16.0)
Requirement already satisfied: optree in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (0.19.0)
Requirement already satisfied: ml-dtypes in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (0.5.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (2026.2.25)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras->keras-tuner) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras->keras-tuner) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->keras->keras-tuner) (0.1.2)

In [164]:
import kerastuner as kt

# Finding Best optimizer :

In [165]:
def build_model(hp):
  model = Sequential()

  model.add(Dense(32,activation = 'relu' , input_dim = 8))

  model.add(Dense(1,activation = 'sigmoid'))

  # Tune the learning rate for the optimizer

  optimizer =  hp.Choice('optimizer',values=['adam','sgd','rmsprop','adadelta'])

  model.compile(optimizer = optimizer  , loss = 'binary_crossentropy' , metrics = ['accuracy'])

  return model

In [166]:
# tuner object :

tuner = kt.RandomSearch(build_model,
                        objective='val_accuracy',
                        max_trials = 5)

Reloading Tuner from ./untitled_project/tuner0.json

In [167]:
tuner.search(x_train,y_train , epochs = 5, validation_data = (x_test,y_test))

In [168]:
tuner.get_best_hyperparameters()[0].values

{'optimizer': 'adam'}

In [169]:
model = tuner.get_best_models(num_models=1)[0]

/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'adam', because it has 2 variables whereas the saved optimizer has 10 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [170]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 32)             │           288 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 321 (1.25 KB)

 Trainable params: 321 (1.25 KB)

 Non-trainable params: 0 (0.00 B)

In [171]:
model.fit(x_train,y_train,batch_size = 32 , epochs = 100 , initial_epoch =6 , validation_data = (x_test , y_test))

Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - accuracy: 0.7704 - loss: 0.5053 - val_accuracy: 0.7662 - val_loss: 0.5233
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7704 - loss: 0.4901 - val_accuracy: 0.7662 - val_loss: 0.5161
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4790 - val_accuracy: 0.7792 - val_loss: 0.5088
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7785 - loss: 0.4706 - val_accuracy: 0.7597 - val_loss: 0.5070
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4633 - val_accuracy: 0.7792 - val_loss: 0.5055
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4581 - val_accuracy: 0.7727 - val_loss: 0.5047
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4545 - val_accuracy: 0.7792 - val_loss: 0.5050
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7818 - loss: 0.4510 - val_accuracy: 0.7857 - val_loss: 0.5041
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7899 - loss: 0.4493 - val_accuracy: 0.7857 - val_loss: 0.5043
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7883 - loss: 0.4461 - val_accuracy: 0.7727 - val_loss: 0.5074
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7883 - loss: 0.4436 - val_accuracy: 0.7792 - val_loss: 0.5077
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4421 - val_accuracy: 0.7727 - val_loss: 0.5098
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7932 - loss: 0.4399 - val_accuracy: 0.7727 - val_loss: 0.5101
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7899 - loss: 0.4386 - val_accuracy: 0.7727 - val_loss: 0.5128
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7899 - loss: 0.4372 - val_accuracy: 0.7727 - val_loss: 0.5147
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4361 - val_accuracy: 0.7597 - val_loss: 0.5156
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4357 - val_accuracy: 0.7662 - val_loss: 0.5157
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4342 - val_accuracy: 0.7597 - val_loss: 0.5194
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7899 - loss: 0.4329 - val_accuracy: 0.7597 - val_loss: 0.5190
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4321 - val_accuracy: 0.7597 - val_loss: 0.5225
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4312 - val_accuracy: 0.7532 - val_loss: 0.5246
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7948 - loss: 0.4302 - val_accuracy: 0.7597 - val_loss: 0.5254
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4295 - val_accuracy: 0.7662 - val_loss: 0.5262
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4289 - val_accuracy: 0.7662 - val_loss: 0.5259
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7932 - loss: 0.4282 - val_accuracy: 0.7662 - val_loss: 0.5265
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4275 - val_accuracy: 0.7597 - val_loss: 0.5274
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4269 - val_accuracy: 0.7597 - val_loss: 0.5286
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4258 - val_accuracy: 0.7597 - val_loss: 0.5292
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4251 - val_accuracy: 0.7597 - val_loss: 0.5300
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4244 - val_accuracy: 0.7597 - val_loss: 0.5316
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7948 - loss: 0.4236 - val_accuracy: 0.7662 - val_loss: 0.5325
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4232 - val_accuracy: 0.7597 - val_loss: 0.5334
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4231 - val_accuracy: 0.7532 - val_loss: 0.5357
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7980 - loss: 0.4221 - val_accuracy: 0.7597 - val_loss: 0.5355
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4213 - val_accuracy: 0.7597 - val_loss: 0.5363
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4210 - val_accuracy: 0.7597 - val_loss: 0.5375
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7915 - loss: 0.4200 - val_accuracy: 0.7597 - val_loss: 0.5383
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4193 - val_accuracy: 0.7597 - val_loss: 0.5396
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4189 - val_accuracy: 0.7532 - val_loss: 0.5428
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4187 - val_accuracy: 0.7662 - val_loss: 0.5433
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7932 - loss: 0.4175 - val_accuracy: 0.7727 - val_loss: 0.5433
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4174 - val_accuracy: 0.7662 - val_loss: 0.5434
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4167 - val_accuracy: 0.7597 - val_loss: 0.5445
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4161 - val_accuracy: 0.7727 - val_loss: 0.5448
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7915 - loss: 0.4160 - val_accuracy: 0.7662 - val_loss: 0.5468
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4154 - val_accuracy: 0.7727 - val_loss: 0.5478
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7932 - loss: 0.4147 - val_accuracy: 0.7727 - val_loss: 0.5478
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7915 - loss: 0.4144 - val_accuracy: 0.7727 - val_loss: 0.5482
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7948 - loss: 0.4137 - val_accuracy: 0.7727 - val_loss: 0.5496
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7932 - loss: 0.4132 - val_accuracy: 0.7727 - val_loss: 0.5495
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7948 - loss: 0.4129 - val_accuracy: 0.7727 - val_loss: 0.5501
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7980 - loss: 0.4124 - val_accuracy: 0.7662 - val_loss: 0.5497
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7980 - loss: 0.4118 - val_accuracy: 0.7727 - val_loss: 0.5496
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7964 - loss: 0.4119 - val_accuracy: 0.7597 - val_loss: 0.5511
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7964 - loss: 0.4110 - val_accuracy: 0.7662 - val_loss: 0.5490
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7948 - loss: 0.4110 - val_accuracy: 0.7597 - val_loss: 0.5536
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8013 - loss: 0.4100 - val_accuracy: 0.7662 - val_loss: 0.5512
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8013 - loss: 0.4094 - val_accuracy: 0.7597 - val_loss: 0.5529
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8062 - loss: 0.4092 - val_accuracy: 0.7662 - val_loss: 0.5541
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8078 - loss: 0.4086 - val_accuracy: 0.7662 - val_loss: 0.5554
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4085 - val_accuracy: 0.7532 - val_loss: 0.5550
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8062 - loss: 0.4077 - val_accuracy: 0.7532 - val_loss: 0.5553
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8094 - loss: 0.4070 - val_accuracy: 0.7532 - val_loss: 0.5559
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8078 - loss: 0.4067 - val_accuracy: 0.7403 - val_loss: 0.5564
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4064 - val_accuracy: 0.7468 - val_loss: 0.5555
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8013 - loss: 0.4061 - val_accuracy: 0.7468 - val_loss: 0.5578
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.4054 - val_accuracy: 0.7468 - val_loss: 0.5602
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8078 - loss: 0.4053 - val_accuracy: 0.7338 - val_loss: 0.5628
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8062 - loss: 0.4050 - val_accuracy: 0.7403 - val_loss: 0.5647
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8111 - loss: 0.4041 - val_accuracy: 0.7338 - val_loss: 0.5628
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8111 - loss: 0.4041 - val_accuracy: 0.7403 - val_loss: 0.5628
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8094 - loss: 0.4035 - val_accuracy: 0.7403 - val_loss: 0.5616
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8062 - loss: 0.4030 - val_accuracy: 0.7403 - val_loss: 0.5625
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8143 - loss: 0.4028 - val_accuracy: 0.7403 - val_loss: 0.5647
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8094 - loss: 0.4022 - val_accuracy: 0.7403 - val_loss: 0.5658
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8127 - loss: 0.4020 - val_accuracy: 0.7403 - val_loss: 0.5655
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8062 - loss: 0.4018 - val_accuracy: 0.7403 - val_loss: 0.5665
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8111 - loss: 0.4011 - val_accuracy: 0.7403 - val_loss: 0.5676
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8078 - loss: 0.4012 - val_accuracy: 0.7338 - val_loss: 0.5665
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8078 - loss: 0.4013 - val_accuracy: 0.7273 - val_loss: 0.5704
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8127 - loss: 0.4002 - val_accuracy: 0.7273 - val_loss: 0.5680
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8143 - loss: 0.3996 - val_accuracy: 0.7338 - val_loss: 0.5677
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8127 - loss: 0.3992 - val_accuracy: 0.7403 - val_loss: 0.5644
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8078 - loss: 0.4002 - val_accuracy: 0.7208 - val_loss: 0.5676
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8078 - loss: 0.3999 - val_accuracy: 0.7338 - val_loss: 0.5649
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8078 - loss: 0.3992 - val_accuracy: 0.7338 - val_loss: 0.5659
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8111 - loss: 0.3981 - val_accuracy: 0.7273 - val_loss: 0.5665
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8143 - loss: 0.3977 - val_accuracy: 0.7273 - val_loss: 0.5692
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8160 - loss: 0.3970 - val_accuracy: 0.7273 - val_loss: 0.5701
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8176 - loss: 0.3970 - val_accuracy: 0.7273 - val_loss: 0.5708
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8160 - loss: 0.3967 - val_accuracy: 0.7338 - val_loss: 0.5707
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8176 - loss: 0.3964 - val_accuracy: 0.7338 - val_loss: 0.5721
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8176 - loss: 0.3960 - val_accuracy: 0.7338 - val_loss: 0.5695
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8192 - loss: 0.3956 - val_accuracy: 0.7338 - val_loss: 0.5724

# Finding best number of neurons in a single llayer :

In [172]:
def build_model_n(hp) :

  model = Sequential()

  units = hp.Int('units' ,min_value = 8, max_value = 128 , step = 8)

  model.add(Dense(units = units , activation = 'relu' , input_dim = 8))

  model.add(Dense(1,activation = 'sigmoid'))

  model.compile(optimizer = 'adam' , loss = 'binary_crossentropy' , metrics= ['accuracy'])

  return model

In [173]:
tuner_n = kt.RandomSearch(build_model_n,
                          objective= 'val_accuracy',
                          max_trials = 5,
                          directory = 'mydir',
                          project_name = 'Ayush')

Reloading Tuner from mydir/Ayush/tuner0.json

In [174]:
tuner_n.search(x_train,y_train , epochs = 5, validation_data = (x_test,y_test))

In [175]:
tuner_n.get_best_hyperparameters()[0].values

{'units': 56}

In [176]:
model = tuner.get_best_models(num_models= 1)[0]

In [177]:
model.fit(x_train,y_train,batch_size = 32 , epochs = 100 , initial_epoch=6, validation_data=(x_test,y_test))

Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - accuracy: 0.7687 - loss: 0.5053 - val_accuracy: 0.7597 - val_loss: 0.5223
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7801 - loss: 0.4905 - val_accuracy: 0.7792 - val_loss: 0.5164
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7801 - loss: 0.4800 - val_accuracy: 0.7662 - val_loss: 0.5113
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7818 - loss: 0.4707 - val_accuracy: 0.7727 - val_loss: 0.5070
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7915 - loss: 0.4642 - val_accuracy: 0.7792 - val_loss: 0.5033
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4589 - val_accuracy: 0.7727 - val_loss: 0.5056
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4549 - val_accuracy: 0.7792 - val_loss: 0.5060
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4513 - val_accuracy: 0.7857 - val_loss: 0.5053
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7866 - loss: 0.4481 - val_accuracy: 0.7857 - val_loss: 0.5054
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7899 - loss: 0.4455 - val_accuracy: 0.7857 - val_loss: 0.5080
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7899 - loss: 0.4432 - val_accuracy: 0.7792 - val_loss: 0.5092
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7883 - loss: 0.4415 - val_accuracy: 0.7727 - val_loss: 0.5095
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7899 - loss: 0.4408 - val_accuracy: 0.7662 - val_loss: 0.5136
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7915 - loss: 0.4387 - val_accuracy: 0.7662 - val_loss: 0.5133
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7915 - loss: 0.4377 - val_accuracy: 0.7662 - val_loss: 0.5122
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7932 - loss: 0.4367 - val_accuracy: 0.7662 - val_loss: 0.5149
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7899 - loss: 0.4352 - val_accuracy: 0.7727 - val_loss: 0.5162
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7915 - loss: 0.4341 - val_accuracy: 0.7662 - val_loss: 0.5178
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7915 - loss: 0.4333 - val_accuracy: 0.7597 - val_loss: 0.5226
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7883 - loss: 0.4321 - val_accuracy: 0.7597 - val_loss: 0.5229
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7883 - loss: 0.4312 - val_accuracy: 0.7662 - val_loss: 0.5232
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7948 - loss: 0.4304 - val_accuracy: 0.7727 - val_loss: 0.5223
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4299 - val_accuracy: 0.7727 - val_loss: 0.5250
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4290 - val_accuracy: 0.7662 - val_loss: 0.5281
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4276 - val_accuracy: 0.7662 - val_loss: 0.5286
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4275 - val_accuracy: 0.7662 - val_loss: 0.5324
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4264 - val_accuracy: 0.7597 - val_loss: 0.5342
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4257 - val_accuracy: 0.7532 - val_loss: 0.5357
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7932 - loss: 0.4251 - val_accuracy: 0.7597 - val_loss: 0.5340
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4246 - val_accuracy: 0.7597 - val_loss: 0.5335
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4234 - val_accuracy: 0.7597 - val_loss: 0.5342
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4228 - val_accuracy: 0.7597 - val_loss: 0.5348
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4223 - val_accuracy: 0.7597 - val_loss: 0.5364
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4213 - val_accuracy: 0.7532 - val_loss: 0.5399
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4214 - val_accuracy: 0.7532 - val_loss: 0.5417
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7915 - loss: 0.4203 - val_accuracy: 0.7532 - val_loss: 0.5421
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4195 - val_accuracy: 0.7597 - val_loss: 0.5382
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4194 - val_accuracy: 0.7727 - val_loss: 0.5399
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4186 - val_accuracy: 0.7597 - val_loss: 0.5430
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4187 - val_accuracy: 0.7532 - val_loss: 0.5448
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4173 - val_accuracy: 0.7597 - val_loss: 0.5451
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4169 - val_accuracy: 0.7727 - val_loss: 0.5442
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4164 - val_accuracy: 0.7662 - val_loss: 0.5461
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4163 - val_accuracy: 0.7727 - val_loss: 0.5466
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4154 - val_accuracy: 0.7597 - val_loss: 0.5497
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4148 - val_accuracy: 0.7662 - val_loss: 0.5464
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7932 - loss: 0.4145 - val_accuracy: 0.7662 - val_loss: 0.5481
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4140 - val_accuracy: 0.7662 - val_loss: 0.5480
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7932 - loss: 0.4133 - val_accuracy: 0.7662 - val_loss: 0.5485
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4132 - val_accuracy: 0.7662 - val_loss: 0.5488
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4130 - val_accuracy: 0.7662 - val_loss: 0.5492
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7948 - loss: 0.4120 - val_accuracy: 0.7662 - val_loss: 0.5499
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4116 - val_accuracy: 0.7597 - val_loss: 0.5494
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4114 - val_accuracy: 0.7662 - val_loss: 0.5525
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7932 - loss: 0.4109 - val_accuracy: 0.7727 - val_loss: 0.5522
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4106 - val_accuracy: 0.7662 - val_loss: 0.5500
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4107 - val_accuracy: 0.7597 - val_loss: 0.5524
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7948 - loss: 0.4101 - val_accuracy: 0.7468 - val_loss: 0.5531
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7964 - loss: 0.4095 - val_accuracy: 0.7597 - val_loss: 0.5535
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4091 - val_accuracy: 0.7532 - val_loss: 0.5531
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7980 - loss: 0.4083 - val_accuracy: 0.7532 - val_loss: 0.5559
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8013 - loss: 0.4085 - val_accuracy: 0.7468 - val_loss: 0.5533
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8046 - loss: 0.4075 - val_accuracy: 0.7597 - val_loss: 0.5558
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8029 - loss: 0.4069 - val_accuracy: 0.7532 - val_loss: 0.5561
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8046 - loss: 0.4067 - val_accuracy: 0.7532 - val_loss: 0.5565
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8062 - loss: 0.4064 - val_accuracy: 0.7468 - val_loss: 0.5560
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8046 - loss: 0.4063 - val_accuracy: 0.7532 - val_loss: 0.5555
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8013 - loss: 0.4051 - val_accuracy: 0.7403 - val_loss: 0.5584
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8013 - loss: 0.4050 - val_accuracy: 0.7403 - val_loss: 0.5588
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8078 - loss: 0.4050 - val_accuracy: 0.7403 - val_loss: 0.5615
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8111 - loss: 0.4043 - val_accuracy: 0.7403 - val_loss: 0.5586
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8111 - loss: 0.4039 - val_accuracy: 0.7338 - val_loss: 0.5617
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8094 - loss: 0.4037 - val_accuracy: 0.7403 - val_loss: 0.5628
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8094 - loss: 0.4027 - val_accuracy: 0.7273 - val_loss: 0.5636
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8143 - loss: 0.4026 - val_accuracy: 0.7338 - val_loss: 0.5635
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8127 - loss: 0.4028 - val_accuracy: 0.7338 - val_loss: 0.5617
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8111 - loss: 0.4022 - val_accuracy: 0.7338 - val_loss: 0.5638
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8078 - loss: 0.4023 - val_accuracy: 0.7273 - val_loss: 0.5669
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8127 - loss: 0.4025 - val_accuracy: 0.7338 - val_loss: 0.5632
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8078 - loss: 0.4011 - val_accuracy: 0.7273 - val_loss: 0.5665
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8127 - loss: 0.4008 - val_accuracy: 0.7273 - val_loss: 0.5660
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8143 - loss: 0.4005 - val_accuracy: 0.7208 - val_loss: 0.5687
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8143 - loss: 0.4002 - val_accuracy: 0.7273 - val_loss: 0.5661
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8160 - loss: 0.3997 - val_accuracy: 0.7273 - val_loss: 0.5674
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8160 - loss: 0.3998 - val_accuracy: 0.7273 - val_loss: 0.5667
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8192 - loss: 0.3987 - val_accuracy: 0.7273 - val_loss: 0.5682
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8192 - loss: 0.3985 - val_accuracy: 0.7208 - val_loss: 0.5691
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8160 - loss: 0.3981 - val_accuracy: 0.7338 - val_loss: 0.5699
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8176 - loss: 0.3978 - val_accuracy: 0.7338 - val_loss: 0.5714
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8160 - loss: 0.3977 - val_accuracy: 0.7338 - val_loss: 0.5710
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8160 - loss: 0.3974 - val_accuracy: 0.7338 - val_loss: 0.5720
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8127 - loss: 0.3973 - val_accuracy: 0.7273 - val_loss: 0.5712
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8143 - loss: 0.3966 - val_accuracy: 0.7338 - val_loss: 0.5739
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8127 - loss: 0.3975 - val_accuracy: 0.7338 - val_loss: 0.5738

# Best number of layers :

In [178]:
def build_model_l(hp):

  model = Sequential()

  model.add(Dense(72,activation='relu' , input_dim = 8))

  for i in range(hp.Int('num_layers',min_value = 1 , max_value = 10)):

    model.add(Dense(72,activation = 'relu'))

  model.add(Dense(1,activation='sigmoid'))

  model.compile(optimizer='adam' , loss = 'binary_crossentropy',metrics=['accuracy'])

  return model

In [179]:
tuner_l = kt.RandomSearch(build_model_l,
                          objective = 'val_accuracy',
                          max_trials = 5,
                          directory = 'mydir',
                          project_name = 'num_of_layers')

Reloading Tuner from mydir/num_of_layers/tuner0.json

In [180]:
tuner_l.search(x_train,y_train,epochs = 5 ,validation_data=(x_test,y_test))

In [181]:
tuner_l.get_best_hyperparameters()[0].values

{'num_layers': 3}

In [182]:
model = tuner_l.get_best_models(num_models=1)[0]

/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'adam', because it has 2 variables whereas the saved optimizer has 22 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [183]:
model.fit(x_train,y_train,epochs=100,initial_epoch=6,validation_data=(x_test,y_test))

Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 2s 17ms/step - accuracy: 0.7752 - loss: 0.4638 - val_accuracy: 0.7403 - val_loss: 0.5133
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7883 - loss: 0.4397 - val_accuracy: 0.7468 - val_loss: 0.5211
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7948 - loss: 0.4250 - val_accuracy: 0.7403 - val_loss: 0.5265
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8078 - loss: 0.4163 - val_accuracy: 0.7662 - val_loss: 0.5360
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7948 - loss: 0.4331 - val_accuracy: 0.7403 - val_loss: 0.5434
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8176 - loss: 0.3993 - val_accuracy: 0.7532 - val_loss: 0.5485
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8176 - loss: 0.4053 - val_accuracy: 0.7208 - val_loss: 0.5585
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8160 - loss: 0.3923 - val_accuracy: 0.7273 - val_loss: 0.5697
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8160 - loss: 0.3940 - val_accuracy: 0.7208 - val_loss: 0.5662
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8306 - loss: 0.3727 - val_accuracy: 0.7273 - val_loss: 0.5788
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8257 - loss: 0.3655 - val_accuracy: 0.7208 - val_loss: 0.5800
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8290 - loss: 0.3584 - val_accuracy: 0.7143 - val_loss: 0.5864
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8404 - loss: 0.3538 - val_accuracy: 0.7208 - val_loss: 0.6033
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8453 - loss: 0.3458 - val_accuracy: 0.7208 - val_loss: 0.6073
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8567 - loss: 0.3362 - val_accuracy: 0.7208 - val_loss: 0.6261
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8550 - loss: 0.3304 - val_accuracy: 0.7208 - val_loss: 0.6253
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8599 - loss: 0.3196 - val_accuracy: 0.7143 - val_loss: 0.6299
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8713 - loss: 0.3104 - val_accuracy: 0.7143 - val_loss: 0.6498
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8876 - loss: 0.2986 - val_accuracy: 0.7273 - val_loss: 0.6535
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8664 - loss: 0.3160 - val_accuracy: 0.7208 - val_loss: 0.6732
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8697 - loss: 0.2916 - val_accuracy: 0.6818 - val_loss: 0.7104
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8697 - loss: 0.2874 - val_accuracy: 0.7208 - val_loss: 0.7244
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8941 - loss: 0.2665 - val_accuracy: 0.7208 - val_loss: 0.7199
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8974 - loss: 0.2680 - val_accuracy: 0.7013 - val_loss: 0.7751
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8941 - loss: 0.2624 - val_accuracy: 0.7338 - val_loss: 0.7765
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8893 - loss: 0.2621 - val_accuracy: 0.7013 - val_loss: 0.7826
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8974 - loss: 0.2529 - val_accuracy: 0.7078 - val_loss: 0.8296
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8876 - loss: 0.2475 - val_accuracy: 0.7143 - val_loss: 0.8071
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9235 - loss: 0.2061 - val_accuracy: 0.6883 - val_loss: 0.9242
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9055 - loss: 0.2166 - val_accuracy: 0.6234 - val_loss: 1.0327
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9104 - loss: 0.2313 - val_accuracy: 0.6753 - val_loss: 0.9652
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9251 - loss: 0.1906 - val_accuracy: 0.6688 - val_loss: 0.9790
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9349 - loss: 0.1752 - val_accuracy: 0.7013 - val_loss: 0.9872
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9463 - loss: 0.1526 - val_accuracy: 0.6688 - val_loss: 1.0564
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9397 - loss: 0.1606 - val_accuracy: 0.6883 - val_loss: 1.0791
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9349 - loss: 0.1591 - val_accuracy: 0.6883 - val_loss: 1.1224
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9365 - loss: 0.1470 - val_accuracy: 0.6948 - val_loss: 1.0917
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9707 - loss: 0.1185 - val_accuracy: 0.7013 - val_loss: 1.2111
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9625 - loss: 0.1294 - val_accuracy: 0.6883 - val_loss: 1.2156
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9691 - loss: 0.1147 - val_accuracy: 0.6688 - val_loss: 1.3786
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9544 - loss: 0.1252 - val_accuracy: 0.6818 - val_loss: 1.3183
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9756 - loss: 0.1053 - val_accuracy: 0.6948 - val_loss: 1.3877
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9609 - loss: 0.1091 - val_accuracy: 0.6818 - val_loss: 1.4017
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9707 - loss: 0.0939 - val_accuracy: 0.6883 - val_loss: 1.4904
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9739 - loss: 0.0888 - val_accuracy: 0.6818 - val_loss: 1.4870
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9788 - loss: 0.0833 - val_accuracy: 0.7078 - val_loss: 1.4876
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9821 - loss: 0.0713 - val_accuracy: 0.6623 - val_loss: 1.6495
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9805 - loss: 0.0691 - val_accuracy: 0.6753 - val_loss: 1.6906
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9756 - loss: 0.0772 - val_accuracy: 0.6364 - val_loss: 1.7016
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9756 - loss: 0.0725 - val_accuracy: 0.6818 - val_loss: 1.6140
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9756 - loss: 0.0721 - val_accuracy: 0.6688 - val_loss: 1.8051
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9853 - loss: 0.0635 - val_accuracy: 0.6688 - val_loss: 1.7115
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9853 - loss: 0.0558 - val_accuracy: 0.6623 - val_loss: 1.8987
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9788 - loss: 0.0680 - val_accuracy: 0.6623 - val_loss: 1.7963
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9772 - loss: 0.0724 - val_accuracy: 0.6883 - val_loss: 1.6670
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9821 - loss: 0.0704 - val_accuracy: 0.6818 - val_loss: 1.9145
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9837 - loss: 0.0623 - val_accuracy: 0.6688 - val_loss: 1.8320
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9821 - loss: 0.0627 - val_accuracy: 0.6753 - val_loss: 1.8295
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9821 - loss: 0.0602 - val_accuracy: 0.6883 - val_loss: 1.9097
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9805 - loss: 0.0558 - val_accuracy: 0.6688 - val_loss: 1.9619
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9756 - loss: 0.0790 - val_accuracy: 0.6818 - val_loss: 1.9382
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9870 - loss: 0.0543 - val_accuracy: 0.6883 - val_loss: 2.0971
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9886 - loss: 0.0461 - val_accuracy: 0.6818 - val_loss: 2.0169
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9723 - loss: 0.0879 - val_accuracy: 0.7013 - val_loss: 1.9091
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9691 - loss: 0.0885 - val_accuracy: 0.6688 - val_loss: 1.8573
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9788 - loss: 0.0555 - val_accuracy: 0.7143 - val_loss: 1.7847
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9837 - loss: 0.0442 - val_accuracy: 0.6818 - val_loss: 1.9913
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9984 - loss: 0.0262 - val_accuracy: 0.6883 - val_loss: 2.0275
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9967 - loss: 0.0200 - val_accuracy: 0.6688 - val_loss: 2.0700
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9984 - loss: 0.0162 - val_accuracy: 0.6883 - val_loss: 2.1612
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.0117 - val_accuracy: 0.6688 - val_loss: 2.2086
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9967 - loss: 0.0126 - val_accuracy: 0.6948 - val_loss: 2.3278
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9984 - loss: 0.0113 - val_accuracy: 0.6818 - val_loss: 2.3742
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9984 - loss: 0.0117 - val_accuracy: 0.6818 - val_loss: 2.3663
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9984 - loss: 0.0135 - val_accuracy: 0.6558 - val_loss: 2.3856
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9967 - loss: 0.0173 - val_accuracy: 0.6818 - val_loss: 2.4807
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9772 - loss: 0.0857 - val_accuracy: 0.7013 - val_loss: 2.2471
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9788 - loss: 0.0716 - val_accuracy: 0.7208 - val_loss: 2.2029
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9886 - loss: 0.0495 - val_accuracy: 0.6883 - val_loss: 2.1308
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9951 - loss: 0.0257 - val_accuracy: 0.6948 - val_loss: 2.2531
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9984 - loss: 0.0115 - val_accuracy: 0.7078 - val_loss: 2.2943
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.0104 - val_accuracy: 0.6948 - val_loss: 2.3936
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.0067 - val_accuracy: 0.6948 - val_loss: 2.3972
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.0056 - val_accuracy: 0.6883 - val_loss: 2.4946
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.0051 - val_accuracy: 0.6818 - val_loss: 2.5081
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.0044 - val_accuracy: 0.6883 - val_loss: 2.5198
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.0041 - val_accuracy: 0.6883 - val_loss: 2.5739
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.0037 - val_accuracy: 0.6818 - val_loss: 2.6062
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.0036 - val_accuracy: 0.6883 - val_loss: 2.6488
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.0043 - val_accuracy: 0.6818 - val_loss: 2.6340
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.0039 - val_accuracy: 0.6883 - val_loss: 2.6306
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9967 - loss: 0.0136 - val_accuracy: 0.6818 - val_loss: 2.6796
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9935 - loss: 0.0319 - val_accuracy: 0.6818 - val_loss: 2.6019
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9707 - loss: 0.1209 - val_accuracy: 0.6558 - val_loss: 2.9472

# finding all best parameters :

In [195]:
def build_model_a(hp):

    model = Sequential()

    for i in range(hp.Int('num_layers', min_value=1, max_value=10)):

        if i == 0:
            model.add(Dense(
                units=hp.Int('units_' + str(i), min_value=8, max_value=128, step=8),
                activation=hp.Choice('activation_' + str(i), values=['relu','tanh','sigmoid']),
                input_dim=8
            ))
            model.add(Dropout(hp.Choice('dropout' +  str(i) , values = [0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9])))
        else:
            model.add(Dense(
                units=hp.Int('units_' + str(i), min_value=8, max_value=128, step=8),
                activation=hp.Choice('activation_' + str(i), values=['relu','tanh','sigmoid'])
            ))
            model.add(Dropout(hp.Choice('dropout' +  str(i) , values = [0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9])))


    model.add(Dense(1, activation='sigmoid'))

    model.compile(
        optimizer=hp.Choice('optimizer', values=['rmsprop','adam','sgd','nadam']),
        loss='binary_crossentropy',
        metrics=['accuracy']
    )

    return model

In [196]:
tuner_a = kt.RandomSearch(build_model_a,
                          objective = 'val_accuracy',
                          max_trials = 3,
                          directory = 'mydir',
                          project_name = 'final')

Reloading Tuner from mydir/final/tuner0.json

In [197]:
tuner_a.search(x_train,y_train,epochs = 5 , validation_data=(x_test,y_test))

In [198]:
tuner_a.get_best_hyperparameters()[0].values

{'num_layers': 9,
 'units_0': 72,
 'activation_0': 'sigmoid',
 'optimizer': 'nadam',
 'units_1': 8,
 'activation_1': 'relu',
 'units_2': 8,
 'activation_2': 'relu',
 'units_3': 8,
 'activation_3': 'relu',
 'units_4': 8,
 'activation_4': 'relu',
 'units_5': 8,
 'activation_5': 'relu',
 'units_6': 8,
 'activation_6': 'relu',
 'units_7': 8,
 'activation_7': 'relu',
 'units_8': 8,
 'activation_8': 'relu'}

In [199]:
model = tuner_a.get_best_models(num_models=1)[0]

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'nadam', because it has 2 variables whereas the saved optimizer has 43 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [200]:
model.fit(x_train,y_train , epochs= 200 , initial_epoch= 6 , validation_data=(x_test,y_test) )

Epoch 7/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 5s 28ms/step - accuracy: 0.6270 - loss: 0.6527 - val_accuracy: 0.8052 - val_loss: 0.5384
Epoch 8/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.6531 - loss: 0.6269 - val_accuracy: 0.7987 - val_loss: 0.5640
Epoch 9/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.6612 - loss: 0.6196 - val_accuracy: 0.6429 - val_loss: 0.5663
Epoch 10/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.6580 - loss: 0.6173 - val_accuracy: 0.6429 - val_loss: 0.5764
Epoch 11/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.6629 - loss: 0.5855 - val_accuracy: 0.6429 - val_loss: 0.5678
Epoch 12/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.6596 - loss: 0.6080 - val_accuracy: 0.6429 - val_loss: 0.5669
Epoch 13/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.6694 - loss: 0.6081 - val_accuracy: 0.6429 - val_loss: 0.5721
Epoch 14/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.6629 - loss: 0.5886 - val_accuracy: 0.6429 - val_loss: 0.5628
Epoch 15/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.6759 - loss: 0.5847 - val_accuracy: 0.7078 - val_loss: 0.5575
Epoch 16/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.6906 - loss: 0.5731 - val_accuracy: 0.8052 - val_loss: 0.5523
Epoch 17/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6840 - loss: 0.5748 - val_accuracy: 0.7662 - val_loss: 0.5476
Epoch 18/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7199 - loss: 0.5494 - val_accuracy: 0.7143 - val_loss: 0.5410
Epoch 19/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6775 - loss: 0.5583 - val_accuracy: 0.7208 - val_loss: 0.5369
Epoch 20/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6792 - loss: 0.5348 - val_accuracy: 0.7013 - val_loss: 0.5349
Epoch 21/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7182 - loss: 0.5373 - val_accuracy: 0.7078 - val_loss: 0.5340
Epoch 22/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7182 - loss: 0.5342 - val_accuracy: 0.7078 - val_loss: 0.5313
Epoch 23/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7313 - loss: 0.5358 - val_accuracy: 0.7143 - val_loss: 0.5302
Epoch 24/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7101 - loss: 0.5321 - val_accuracy: 0.7143 - val_loss: 0.5262
Epoch 25/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7329 - loss: 0.5378 - val_accuracy: 0.6883 - val_loss: 0.5351
Epoch 26/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7182 - loss: 0.5062 - val_accuracy: 0.7078 - val_loss: 0.5280
Epoch 27/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7036 - loss: 0.5408 - val_accuracy: 0.7013 - val_loss: 0.5250
Epoch 28/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7492 - loss: 0.5266 - val_accuracy: 0.7338 - val_loss: 0.5267
Epoch 29/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7410 - loss: 0.5234 - val_accuracy: 0.7403 - val_loss: 0.5178
Epoch 30/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7313 - loss: 0.5229 - val_accuracy: 0.7273 - val_loss: 0.5184
Epoch 31/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7313 - loss: 0.5147 - val_accuracy: 0.7273 - val_loss: 0.5192
Epoch 32/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7329 - loss: 0.5214 - val_accuracy: 0.7338 - val_loss: 0.5139
Epoch 33/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7394 - loss: 0.5237 - val_accuracy: 0.7468 - val_loss: 0.5123
Epoch 34/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7443 - loss: 0.5118 - val_accuracy: 0.7403 - val_loss: 0.5154
Epoch 35/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7606 - loss: 0.4852 - val_accuracy: 0.7597 - val_loss: 0.5108
Epoch 36/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7362 - loss: 0.5259 - val_accuracy: 0.7662 - val_loss: 0.5090
Epoch 37/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7459 - loss: 0.5085 - val_accuracy: 0.7078 - val_loss: 0.5217
Epoch 38/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7264 - loss: 0.5247 - val_accuracy: 0.6948 - val_loss: 0.5243
Epoch 39/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7508 - loss: 0.5107 - val_accuracy: 0.7468 - val_loss: 0.5161
Epoch 40/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7590 - loss: 0.5174 - val_accuracy: 0.7403 - val_loss: 0.5154
Epoch 41/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7378 - loss: 0.4982 - val_accuracy: 0.7013 - val_loss: 0.5208
Epoch 42/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7492 - loss: 0.5057 - val_accuracy: 0.7013 - val_loss: 0.5207
Epoch 43/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7508 - loss: 0.4968 - val_accuracy: 0.7403 - val_loss: 0.5134
Epoch 44/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7606 - loss: 0.4647 - val_accuracy: 0.6948 - val_loss: 0.5333
Epoch 45/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7345 - loss: 0.5067 - val_accuracy: 0.7208 - val_loss: 0.5235
Epoch 46/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7296 - loss: 0.5069 - val_accuracy: 0.7143 - val_loss: 0.5212
Epoch 47/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7671 - loss: 0.4905 - val_accuracy: 0.7662 - val_loss: 0.5054
Epoch 48/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7524 - loss: 0.5091 - val_accuracy: 0.7338 - val_loss: 0.5133
Epoch 49/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7492 - loss: 0.5011 - val_accuracy: 0.7338 - val_loss: 0.5130
Epoch 50/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7524 - loss: 0.4948 - val_accuracy: 0.7468 - val_loss: 0.5077
Epoch 51/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7687 - loss: 0.5280 - val_accuracy: 0.7468 - val_loss: 0.5098
Epoch 52/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7541 - loss: 0.5007 - val_accuracy: 0.7403 - val_loss: 0.5084
Epoch 53/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7508 - loss: 0.5155 - val_accuracy: 0.7273 - val_loss: 0.5111
Epoch 54/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7704 - loss: 0.4856 - val_accuracy: 0.7273 - val_loss: 0.5118
Epoch 55/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7394 - loss: 0.4985 - val_accuracy: 0.7662 - val_loss: 0.5034
Epoch 56/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7606 - loss: 0.4917 - val_accuracy: 0.7727 - val_loss: 0.4987
Epoch 57/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7557 - loss: 0.5030 - val_accuracy: 0.7857 - val_loss: 0.4943
Epoch 58/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7280 - loss: 0.5010 - val_accuracy: 0.7792 - val_loss: 0.4964
Epoch 59/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7524 - loss: 0.4947 - val_accuracy: 0.7468 - val_loss: 0.5102
Epoch 60/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7606 - loss: 0.4928 - val_accuracy: 0.7403 - val_loss: 0.5114
Epoch 61/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7459 - loss: 0.5066 - val_accuracy: 0.7597 - val_loss: 0.5044
Epoch 62/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7459 - loss: 0.4980 - val_accuracy: 0.7597 - val_loss: 0.4995
Epoch 63/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7541 - loss: 0.4994 - val_accuracy: 0.7338 - val_loss: 0.5101
Epoch 64/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7508 - loss: 0.5051 - val_accuracy: 0.7727 - val_loss: 0.4983
Epoch 65/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7622 - loss: 0.5030 - val_accuracy: 0.7727 - val_loss: 0.5002
Epoch 66/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7378 - loss: 0.4960 - val_accuracy: 0.7532 - val_loss: 0.5039
Epoch 67/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7671 - loss: 0.4928 - val_accuracy: 0.7208 - val_loss: 0.5141
Epoch 68/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7752 - loss: 0.4930 - val_accuracy: 0.7078 - val_loss: 0.5233
Epoch 69/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7655 - loss: 0.5006 - val_accuracy: 0.7208 - val_loss: 0.5134
Epoch 70/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7541 - loss: 0.5130 - val_accuracy: 0.7468 - val_loss: 0.5134
Epoch 71/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7524 - loss: 0.4929 - val_accuracy: 0.7662 - val_loss: 0.4949
Epoch 72/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7573 - loss: 0.4925 - val_accuracy: 0.7532 - val_loss: 0.5004
Epoch 73/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7769 - loss: 0.4851 - val_accuracy: 0.7403 - val_loss: 0.5036
Epoch 74/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7573 - loss: 0.5018 - val_accuracy: 0.7338 - val_loss: 0.5039
Epoch 75/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7394 - loss: 0.5186 - val_accuracy: 0.7338 - val_loss: 0.5043
Epoch 76/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7492 - loss: 0.4871 - val_accuracy: 0.7338 - val_loss: 0.5106
Epoch 77/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7476 - loss: 0.4938 - val_accuracy: 0.6948 - val_loss: 0.5193
Epoch 78/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7752 - loss: 0.4754 - val_accuracy: 0.7338 - val_loss: 0.5084
Epoch 79/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7524 - loss: 0.4923 - val_accuracy: 0.7273 - val_loss: 0.5139
Epoch 80/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7524 - loss: 0.5020 - val_accuracy: 0.7273 - val_loss: 0.5132
Epoch 81/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7590 - loss: 0.5209 - val_accuracy: 0.7403 - val_loss: 0.5123
Epoch 82/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7687 - loss: 0.4874 - val_accuracy: 0.7208 - val_loss: 0.5160
Epoch 83/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7394 - loss: 0.5007 - val_accuracy: 0.7273 - val_loss: 0.5164
Epoch 84/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7492 - loss: 0.5029 - val_accuracy: 0.7597 - val_loss: 0.5029
Epoch 85/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7459 - loss: 0.4969 - val_accuracy: 0.7597 - val_loss: 0.5050
Epoch 86/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7801 - loss: 0.4823 - val_accuracy: 0.7273 - val_loss: 0.5110
Epoch 87/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7752 - loss: 0.4898 - val_accuracy: 0.7468 - val_loss: 0.5101
Epoch 88/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7557 - loss: 0.4890 - val_accuracy: 0.7468 - val_loss: 0.5119
Epoch 89/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7606 - loss: 0.4973 - val_accuracy: 0.7468 - val_loss: 0.5069
Epoch 90/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7720 - loss: 0.4848 - val_accuracy: 0.7468 - val_loss: 0.5053
Epoch 91/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7508 - loss: 0.4772 - val_accuracy: 0.7468 - val_loss: 0.5070
Epoch 92/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7638 - loss: 0.4971 - val_accuracy: 0.7468 - val_loss: 0.5060
Epoch 93/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7590 - loss: 0.4975 - val_accuracy: 0.7403 - val_loss: 0.5052
Epoch 94/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7687 - loss: 0.5038 - val_accuracy: 0.7338 - val_loss: 0.5086
Epoch 95/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7378 - loss: 0.4800 - val_accuracy: 0.7208 - val_loss: 0.5104
Epoch 96/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7818 - loss: 0.4699 - val_accuracy: 0.7468 - val_loss: 0.5062
Epoch 97/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7687 - loss: 0.4948 - val_accuracy: 0.7468 - val_loss: 0.5056
Epoch 98/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7590 - loss: 0.4720 - val_accuracy: 0.7403 - val_loss: 0.5066
Epoch 99/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7769 - loss: 0.4847 - val_accuracy: 0.7338 - val_loss: 0.5081
Epoch 100/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7655 - loss: 0.4925 - val_accuracy: 0.7792 - val_loss: 0.4936
Epoch 101/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7638 - loss: 0.4830 - val_accuracy: 0.7532 - val_loss: 0.5007
Epoch 102/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7622 - loss: 0.4802 - val_accuracy: 0.7273 - val_loss: 0.5053
Epoch 103/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7476 - loss: 0.5057 - val_accuracy: 0.7273 - val_loss: 0.5035
Epoch 104/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7834 - loss: 0.4682 - val_accuracy: 0.7468 - val_loss: 0.4994
Epoch 105/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7541 - loss: 0.4895 - val_accuracy: 0.7662 - val_loss: 0.4963
Epoch 106/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7932 - loss: 0.4660 - val_accuracy: 0.7338 - val_loss: 0.5018
Epoch 107/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7785 - loss: 0.4702 - val_accuracy: 0.7338 - val_loss: 0.5077
Epoch 108/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7704 - loss: 0.4827 - val_accuracy: 0.7208 - val_loss: 0.5137
Epoch 109/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7459 - loss: 0.5084 - val_accuracy: 0.7208 - val_loss: 0.5138
Epoch 110/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7524 - loss: 0.4858 - val_accuracy: 0.7143 - val_loss: 0.5144
Epoch 111/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7573 - loss: 0.4723 - val_accuracy: 0.7403 - val_loss: 0.5094
Epoch 112/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7752 - loss: 0.4895 - val_accuracy: 0.7532 - val_loss: 0.5080
Epoch 113/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7655 - loss: 0.4971 - val_accuracy: 0.7468 - val_loss: 0.5072
Epoch 114/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7638 - loss: 0.4704 - val_accuracy: 0.7403 - val_loss: 0.5123
Epoch 115/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7362 - loss: 0.4829 - val_accuracy: 0.7338 - val_loss: 0.5138
Epoch 116/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7492 - loss: 0.4928 - val_accuracy: 0.7143 - val_loss: 0.5140
Epoch 117/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7801 - loss: 0.4501 - val_accuracy: 0.7338 - val_loss: 0.5141
Epoch 118/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7899 - loss: 0.4661 - val_accuracy: 0.7078 - val_loss: 0.5228
Epoch 119/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7541 - loss: 0.4877 - val_accuracy: 0.7143 - val_loss: 0.5207
Epoch 120/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7622 - loss: 0.4945 - val_accuracy: 0.7403 - val_loss: 0.5137
Epoch 121/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7638 - loss: 0.4710 - val_accuracy: 0.7468 - val_loss: 0.5136
Epoch 122/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7638 - loss: 0.4675 - val_accuracy: 0.7338 - val_loss: 0.5170
Epoch 123/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7590 - loss: 0.5018 - val_accuracy: 0.7403 - val_loss: 0.5160
Epoch 124/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7476 - loss: 0.4876 - val_accuracy: 0.7403 - val_loss: 0.5161
Epoch 125/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7443 - loss: 0.4808 - val_accuracy: 0.7532 - val_loss: 0.5117
Epoch 126/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7704 - loss: 0.4794 - val_accuracy: 0.7403 - val_loss: 0.5117
Epoch 127/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7476 - loss: 0.4826 - val_accuracy: 0.7338 - val_loss: 0.5128
Epoch 128/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7557 - loss: 0.5012 - val_accuracy: 0.7532 - val_loss: 0.5062
Epoch 129/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - accuracy: 0.7541 - loss: 0.4591 - val_accuracy: 0.7532 - val_loss: 0.5123
Epoch 130/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7638 - loss: 0.4859 - val_accuracy: 0.7403 - val_loss: 0.5132
Epoch 131/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7606 - loss: 0.4813 - val_accuracy: 0.7273 - val_loss: 0.5133
Epoch 132/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7459 - loss: 0.4654 - val_accuracy: 0.7273 - val_loss: 0.5205
Epoch 133/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7704 - loss: 0.4738 - val_accuracy: 0.7532 - val_loss: 0.5187
Epoch 134/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7720 - loss: 0.4684 - val_accuracy: 0.7338 - val_loss: 0.5151
Epoch 135/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7313 - loss: 0.4915 - val_accuracy: 0.7208 - val_loss: 0.5188
Epoch 136/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7573 - loss: 0.4783 - val_accuracy: 0.7143 - val_loss: 0.5179
Epoch 137/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7655 - loss: 0.4836 - val_accuracy: 0.7597 - val_loss: 0.5164
Epoch 138/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7492 - loss: 0.4798 - val_accuracy: 0.7273 - val_loss: 0.5161
Epoch 139/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7687 - loss: 0.4865 - val_accuracy: 0.7273 - val_loss: 0.5133
Epoch 140/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7671 - loss: 0.4678 - val_accuracy: 0.7597 - val_loss: 0.5114
Epoch 141/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7785 - loss: 0.4712 - val_accuracy: 0.7597 - val_loss: 0.5089
Epoch 142/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7622 - loss: 0.4770 - val_accuracy: 0.7532 - val_loss: 0.5064
Epoch 143/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7655 - loss: 0.4666 - val_accuracy: 0.7532 - val_loss: 0.5073
Epoch 144/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7899 - loss: 0.4609 - val_accuracy: 0.7597 - val_loss: 0.5082
Epoch 145/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7752 - loss: 0.4743 - val_accuracy: 0.7532 - val_loss: 0.5049
Epoch 146/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7818 - loss: 0.4696 - val_accuracy: 0.7468 - val_loss: 0.5023
Epoch 147/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7541 - loss: 0.4607 - val_accuracy: 0.7338 - val_loss: 0.5063
Epoch 148/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7769 - loss: 0.4685 - val_accuracy: 0.7468 - val_loss: 0.5058
Epoch 149/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7655 - loss: 0.4662 - val_accuracy: 0.7338 - val_loss: 0.5088
Epoch 150/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7801 - loss: 0.4563 - val_accuracy: 0.7338 - val_loss: 0.5111
Epoch 151/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7655 - loss: 0.4776 - val_accuracy: 0.7273 - val_loss: 0.5147
Epoch 152/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7671 - loss: 0.4727 - val_accuracy: 0.7532 - val_loss: 0.5097
Epoch 153/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7736 - loss: 0.4426 - val_accuracy: 0.7468 - val_loss: 0.5107
Epoch 154/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7801 - loss: 0.4687 - val_accuracy: 0.7532 - val_loss: 0.5044
Epoch 155/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7508 - loss: 0.4795 - val_accuracy: 0.7468 - val_loss: 0.5089
Epoch 156/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7638 - loss: 0.4665 - val_accuracy: 0.7208 - val_loss: 0.5203
Epoch 157/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7932 - loss: 0.4633 - val_accuracy: 0.7403 - val_loss: 0.5070
Epoch 158/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7704 - loss: 0.4713 - val_accuracy: 0.7468 - val_loss: 0.4994
Epoch 159/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7606 - loss: 0.4624 - val_accuracy: 0.7338 - val_loss: 0.5049
Epoch 160/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7590 - loss: 0.4796 - val_accuracy: 0.7532 - val_loss: 0.5013
Epoch 161/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7492 - loss: 0.4823 - val_accuracy: 0.7468 - val_loss: 0.4993
Epoch 162/200